public with sharing class TestGitHubClass {
    public TestGitHubClass() {
        //adding changes via first branch
        string variable = '';
    }
    public void addedNewMethod(){
        for(integer i =0;i<5; i++){
            system.debug('changed apex class'+i);
            system.debug('featured branch'+i);
            //verify if PR is getting validated or not
            //check if PR is getting validated or not
        }
    }
}