name: Validate PR in Scratch Org

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ dev_* ]
    paths:
      - 'force-app/**'

jobs:
  validate-pr-in-scratch-org:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Scratch Org
        run: |
          sfdx auth:jwt:grant --clientid ${SFDX_HUB_CLIENT_ID} --username ${SFDX_HUB_USERNAME} --jwtkeyfile ${SFDX_HUB_JWT_KEY_FILE}
          sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -v

      - name: Push Source to Scratch Org
        run: |
          sfdx force:source:push -f force-app -u scratch-org

      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run -u scratch-org -r human

      - name: Validate Metadata
        run: |
          sfdx force:mdapi:validate -u scratch-org -m force-app/main/default

      - name: Delete Scratch Org
        run: |
          sfdx force:org:delete -u scratch-org